//-----------------------------------------------------------------------------
// Copyright (c) 2018 Semiconductor Components Industries LLC
// (d/b/a "ON Semiconductor").  All rights reserved.
// This software and/or documentation is licensed by ON Semiconductor under
// limited terms and conditions.  The terms and conditions pertaining to the
// software and/or documentation are available at
// http://www.onsemi.com/site/pdf/ONSEMI_T&C.pdf ("ON Semiconductor Standard
// Terms and Conditions of Sale, Section 8 Software") and if applicable the
// software license agreement.  Do not use this software and/or documentation
// unless you have carefully read and you agree to the limited terms and
// conditions.  By using this software and/or documentation, you agree to the
// limited terms and conditions.
//-----------------------------------------------------------------------------
//! \file RTE_HB_BUTTON.h
//!
//!
//! These options can be edited by opening this file in CMSIS Configuration
//! Wizard Editor that is part of Eclipse installation.
//!
//!
//!
//-----------------------------------------------------------------------------

#ifndef RTE_HB_BUTTON_H_
#define RTE_HB_BUTTON_H_

// <<< Use Configuration Wizard in Context Menu >>>

// <e> Button 0 Interrupt Enable
// <i> Enables Interrupt support for button 0 of HB-GEVB.
#define RTE_BUTTON_HB_BTN0_INT_ENABLE  1

// <o> BTN0 Interrupt Source
// <i> Determines which of the four DIO Interrupt Configuration registers to use for button 0.
// <i> Default: 0
//   <0=> 0
//   <1=> 1
//   <2=> 2
//   <3=> 3
#define RTE_BUTTON_HB_BTN0_INT_SRC  0

// <o> BTN0 EventCallback ID <0-65535>
// <i> This number identifies events generated by this button.
// <i> It has to be unique among all used EventCallback event sources.
// <i> Default: 15
#define RTE_BUTTON_HB_BTN0_EVENT_ID  15

// </e>

// <e> Button 1 Interrupt Enable
// <i> Enables Interrupt support for button 1 of HB-GEVB.
#define RTE_BUTTON_HB_BTN1_INT_ENABLE  1

// <o> BTN0 Interrupt Source
// <i> Determines which of the four DIO Interrupt Configuration registers to use for button 1.
// <i> Default: 1
//   <0=> 0
//   <1=> 1
//   <2=> 2
//   <3=> 3
#define RTE_BUTTON_HB_BTN1_INT_SRC  1

// <o> BTN0 EventCallback ID <0-65535>
// <i> This number identifies events generated by this button.
// <i> It has to be unique among all used EventCallback event sources.
// <i> Default: 12
#define RTE_BUTTON_HB_BTN1_EVENT_ID  12

// </e>

// <<< end of configuration section >>>


// Check if configuration is valid
#if RTE_BUTTON_HB_BTN0_INT_ENABLE == 1 && RTE_BUTTON_HB_BTN1_INT_ENABLE == 1
#if RTE_BUTTON_HB_BTN0_INT_SRC == RTE_BUTTON_HB_BTN1_INT_SRC
#error Button interrupts have to be sourced from different INT sources.
#endif /* RTE_BUTTON_HB_BTN0_INT_SRC == RTE_BUTTON_HB_BTN1_INT_SRC */
#endif /* RTE_BUTTON_HB_BTN0_INT_ENABLE == 1 && RTE_BUTTON_HB_BTN1_INT_ENABLE == 1 */


#endif /* RTE_HB_BUTTON_H_ */
